/* Auto-generated from quickjs-atom.h: 227 built-in atoms */
#define QJS_BUILTIN_ATOM_COUNT 228 /* +1 for JS_ATOM_NULL at index 0 */

static const char *qjs_builtin_atoms[] = {
    NULL, /* index 0 = JS_ATOM_NULL */
    "null", /* index 1 */
    "false", /* index 2 */
    "true", /* index 3 */
    "if", /* index 4 */
    "else", /* index 5 */
    "return", /* index 6 */
    "var", /* index 7 */
    "this", /* index 8 */
    "delete", /* index 9 */
    "void", /* index 10 */
    "typeof", /* index 11 */
    "new", /* index 12 */
    "in", /* index 13 */
    "instanceof", /* index 14 */
    "do", /* index 15 */
    "while", /* index 16 */
    "for", /* index 17 */
    "break", /* index 18 */
    "continue", /* index 19 */
    "switch", /* index 20 */
    "case", /* index 21 */
    "default", /* index 22 */
    "throw", /* index 23 */
    "try", /* index 24 */
    "catch", /* index 25 */
    "finally", /* index 26 */
    "function", /* index 27 */
    "debugger", /* index 28 */
    "with", /* index 29 */
    "class", /* index 30 */
    "const", /* index 31 */
    "enum", /* index 32 */
    "export", /* index 33 */
    "extends", /* index 34 */
    "import", /* index 35 */
    "super", /* index 36 */
    "implements", /* index 37 */
    "interface", /* index 38 */
    "let", /* index 39 */
    "package", /* index 40 */
    "private", /* index 41 */
    "protected", /* index 42 */
    "public", /* index 43 */
    "static", /* index 44 */
    "yield", /* index 45 */
    "await", /* index 46 */
    "", /* index 47 */
    "length", /* index 48 */
    "fileName", /* index 49 */
    "lineNumber", /* index 50 */
    "message", /* index 51 */
    "cause", /* index 52 */
    "errors", /* index 53 */
    "stack", /* index 54 */
    "prepareStackTrace", /* index 55 */
    "name", /* index 56 */
    "toString", /* index 57 */
    "toLocaleString", /* index 58 */
    "valueOf", /* index 59 */
    "eval", /* index 60 */
    "prototype", /* index 61 */
    "constructor", /* index 62 */
    "configurable", /* index 63 */
    "writable", /* index 64 */
    "enumerable", /* index 65 */
    "value", /* index 66 */
    "get", /* index 67 */
    "set", /* index 68 */
    "of", /* index 69 */
    "__proto__", /* index 70 */
    "undefined", /* index 71 */
    "number", /* index 72 */
    "boolean", /* index 73 */
    "string", /* index 74 */
    "object", /* index 75 */
    "symbol", /* index 76 */
    "integer", /* index 77 */
    "unknown", /* index 78 */
    "arguments", /* index 79 */
    "callee", /* index 80 */
    "caller", /* index 81 */
    "<eval>", /* index 82 */
    "<ret>", /* index 83 */
    "<var>", /* index 84 */
    "<arg_var>", /* index 85 */
    "<with>", /* index 86 */
    "lastIndex", /* index 87 */
    "target", /* index 88 */
    "index", /* index 89 */
    "input", /* index 90 */
    "defineProperties", /* index 91 */
    "apply", /* index 92 */
    "join", /* index 93 */
    "concat", /* index 94 */
    "split", /* index 95 */
    "construct", /* index 96 */
    "getPrototypeOf", /* index 97 */
    "setPrototypeOf", /* index 98 */
    "isExtensible", /* index 99 */
    "preventExtensions", /* index 100 */
    "has", /* index 101 */
    "deleteProperty", /* index 102 */
    "defineProperty", /* index 103 */
    "getOwnPropertyDescriptor", /* index 104 */
    "ownKeys", /* index 105 */
    "add", /* index 106 */
    "done", /* index 107 */
    "next", /* index 108 */
    "values", /* index 109 */
    "source", /* index 110 */
    "flags", /* index 111 */
    "global", /* index 112 */
    "unicode", /* index 113 */
    "raw", /* index 114 */
    "new.target", /* index 115 */
    "this.active_func", /* index 116 */
    "<home_object>", /* index 117 */
    "<computed_field>", /* index 118 */
    "<static_computed_field>", /* index 119 */
    "<class_fields_init>", /* index 120 */
    "<brand>", /* index 121 */
    "#constructor", /* index 122 */
    "as", /* index 123 */
    "from", /* index 124 */
    "meta", /* index 125 */
    "*default*", /* index 126 */
    "*", /* index 127 */
    "Module", /* index 128 */
    "then", /* index 129 */
    "resolve", /* index 130 */
    "reject", /* index 131 */
    "promise", /* index 132 */
    "proxy", /* index 133 */
    "revoke", /* index 134 */
    "async", /* index 135 */
    "exec", /* index 136 */
    "groups", /* index 137 */
    "indices", /* index 138 */
    "status", /* index 139 */
    "reason", /* index 140 */
    "globalThis", /* index 141 */
    "bigint", /* index 142 */
    "bigfloat", /* index 143 */
    "bigdecimal", /* index 144 */
    "roundingMode", /* index 145 */
    "maximumSignificantDigits", /* index 146 */
    "maximumFractionDigits", /* index 147 */
    "not-equal", /* index 148 */
    "timed-out", /* index 149 */
    "ok", /* index 150 */
    "toJSON", /* index 151 */
    "Object", /* index 152 */
    "Array", /* index 153 */
    "Error", /* index 154 */
    "Number", /* index 155 */
    "String", /* index 156 */
    "Boolean", /* index 157 */
    "Symbol", /* index 158 */
    "Arguments", /* index 159 */
    "Math", /* index 160 */
    "JSON", /* index 161 */
    "Date", /* index 162 */
    "Function", /* index 163 */
    "GeneratorFunction", /* index 164 */
    "ForInIterator", /* index 165 */
    "RegExp", /* index 166 */
    "ArrayBuffer", /* index 167 */
    "SharedArrayBuffer", /* index 168 */
    "Uint8ClampedArray", /* index 169 */
    "Int8Array", /* index 170 */
    "Uint8Array", /* index 171 */
    "Int16Array", /* index 172 */
    "Uint16Array", /* index 173 */
    "Int32Array", /* index 174 */
    "Uint32Array", /* index 175 */
    "BigInt64Array", /* index 176 */
    "BigUint64Array", /* index 177 */
    "Float32Array", /* index 178 */
    "Float64Array", /* index 179 */
    "DataView", /* index 180 */
    "BigInt", /* index 181 */
    "BigFloat", /* index 182 */
    "BigFloatEnv", /* index 183 */
    "BigDecimal", /* index 184 */
    "OperatorSet", /* index 185 */
    "Operators", /* index 186 */
    "Map", /* index 187 */
    "Set", /* index 188 */
    "WeakMap", /* index 189 */
    "WeakSet", /* index 190 */
    "Map Iterator", /* index 191 */
    "Set Iterator", /* index 192 */
    "Array Iterator", /* index 193 */
    "String Iterator", /* index 194 */
    "RegExp String Iterator", /* index 195 */
    "Generator", /* index 196 */
    "Proxy", /* index 197 */
    "Promise", /* index 198 */
    "PromiseResolveFunction", /* index 199 */
    "PromiseRejectFunction", /* index 200 */
    "AsyncFunction", /* index 201 */
    "AsyncFunctionResolve", /* index 202 */
    "AsyncFunctionReject", /* index 203 */
    "AsyncGeneratorFunction", /* index 204 */
    "AsyncGenerator", /* index 205 */
    "EvalError", /* index 206 */
    "RangeError", /* index 207 */
    "ReferenceError", /* index 208 */
    "SyntaxError", /* index 209 */
    "TypeError", /* index 210 */
    "URIError", /* index 211 */
    "InternalError", /* index 212 */
    "<brand>", /* index 213 */
    "Symbol.toPrimitive", /* index 214 */
    "Symbol.iterator", /* index 215 */
    "Symbol.match", /* index 216 */
    "Symbol.matchAll", /* index 217 */
    "Symbol.replace", /* index 218 */
    "Symbol.search", /* index 219 */
    "Symbol.split", /* index 220 */
    "Symbol.toStringTag", /* index 221 */
    "Symbol.isConcatSpreadable", /* index 222 */
    "Symbol.hasInstance", /* index 223 */
    "Symbol.species", /* index 224 */
    "Symbol.unscopables", /* index 225 */
    "Symbol.asyncIterator", /* index 226 */
    "Symbol.operatorSet", /* index 227 */
};
