/*
 * qjs_opcodes.h - QuickJS opcode definitions (standalone, no QuickJS deps)
 *
 * This is a clean re-implementation of quickjs-opcode.h, providing:
 *   - OpFmt: operand format enum
 *   - qjs_op_info_t: per-opcode info (name, size, pop, push, fmt)
 *   - qjs_op_info[]: static table indexed by opcode value
 *
 * Part of the JARONA decompiler.
 */
#ifndef QJS_OPCODES_H
#define QJS_OPCODES_H

#include <stdint.h>

/* =========================================================
 * Operand format
 * ========================================================= */
typedef enum {
    QJS_FMT_none,
    QJS_FMT_none_int,
    QJS_FMT_none_loc,
    QJS_FMT_none_arg,
    QJS_FMT_none_var_ref,
    QJS_FMT_u8,
    QJS_FMT_i8,
    QJS_FMT_loc8,
    QJS_FMT_const8,
    QJS_FMT_label8,
    QJS_FMT_u16,
    QJS_FMT_i16,
    QJS_FMT_label16,
    QJS_FMT_npop,
    QJS_FMT_npopx,
    QJS_FMT_npop_u16,
    QJS_FMT_loc,
    QJS_FMT_arg,
    QJS_FMT_var_ref,
    QJS_FMT_u32,
    QJS_FMT_i32,
    QJS_FMT_const,
    QJS_FMT_label,
    QJS_FMT_atom,
    QJS_FMT_atom_u8,
    QJS_FMT_atom_u16,
    QJS_FMT_atom_label_u8,
    QJS_FMT_atom_label_u16,
    QJS_FMT_label_u16,
} qjs_op_fmt_t;

/* =========================================================
 * Opcode info record
 * ========================================================= */
typedef struct {
    const char *name;
    uint8_t     size;
    int8_t      n_pop;       /* -1 = variable */
    int8_t      n_push;      /* -1 = variable */
    qjs_op_fmt_t fmt;
} qjs_op_info_t;

/* opcode enumeration - mirrors quickjs-opcode.h order */
enum {
    qjs_op_invalid = 0,
    qjs_op_push_i32,
    qjs_op_push_const,
    qjs_op_fclosure,
    qjs_op_push_atom_value,
    qjs_op_private_symbol,
    qjs_op_undefined,
    qjs_op_null,
    qjs_op_push_this,
    qjs_op_push_false,
    qjs_op_push_true,
    qjs_op_object,
    qjs_op_special_object,
    qjs_op_rest,
    qjs_op_drop,
    qjs_op_nip,
    qjs_op_nip1,
    qjs_op_dup,
    qjs_op_dup1,
    qjs_op_dup2,
    qjs_op_dup3,
    qjs_op_insert2,
    qjs_op_insert3,
    qjs_op_insert4,
    qjs_op_perm3,
    qjs_op_perm4,
    qjs_op_perm5,
    qjs_op_swap,
    qjs_op_swap2,
    qjs_op_rot3l,
    qjs_op_rot3r,
    qjs_op_rot4l,
    qjs_op_rot5l,
    qjs_op_call_constructor,
    qjs_op_call,
    qjs_op_tail_call,
    qjs_op_call_method,
    qjs_op_tail_call_method,
    qjs_op_array_from,
    qjs_op_apply,
    qjs_op_return,
    qjs_op_return_undef,
    qjs_op_check_ctor_return,
    qjs_op_check_ctor,
    qjs_op_check_brand,
    qjs_op_add_brand,
    qjs_op_return_async,
    qjs_op_throw,
    qjs_op_throw_error,
    qjs_op_eval,
    qjs_op_apply_eval,
    qjs_op_regexp,
    qjs_op_get_super,
    qjs_op_import,
    qjs_op_check_var,
    qjs_op_get_var_undef,
    qjs_op_get_var,
    qjs_op_put_var,
    qjs_op_put_var_init,
    qjs_op_put_var_strict,
    qjs_op_get_ref_value,
    qjs_op_put_ref_value,
    qjs_op_define_var,
    qjs_op_check_define_var,
    qjs_op_define_func,
    qjs_op_get_field,
    qjs_op_get_field2,
    qjs_op_put_field,
    qjs_op_get_private_field,
    qjs_op_put_private_field,
    qjs_op_define_private_field,
    qjs_op_get_array_el,
    qjs_op_get_array_el2,
    qjs_op_put_array_el,
    qjs_op_get_super_value,
    qjs_op_put_super_value,
    qjs_op_define_field,
    qjs_op_set_name,
    qjs_op_set_name_computed,
    qjs_op_set_proto,
    qjs_op_set_home_object,
    qjs_op_define_array_el,
    qjs_op_append,
    qjs_op_copy_data_properties,
    qjs_op_define_method,
    qjs_op_define_method_computed,
    qjs_op_define_class,
    qjs_op_define_class_computed,
    qjs_op_get_loc,
    qjs_op_put_loc,
    qjs_op_set_loc,
    qjs_op_get_arg,
    qjs_op_put_arg,
    qjs_op_set_arg,
    qjs_op_get_var_ref,
    qjs_op_put_var_ref,
    qjs_op_set_var_ref,
    qjs_op_set_loc_uninitialized,
    qjs_op_get_loc_check,
    qjs_op_put_loc_check,
    qjs_op_put_loc_check_init,
    qjs_op_get_loc_checkthis,
    qjs_op_get_var_ref_check,
    qjs_op_put_var_ref_check,
    qjs_op_put_var_ref_check_init,
    qjs_op_close_loc,
    qjs_op_if_false,
    qjs_op_if_true,
    qjs_op_goto,
    qjs_op_catch,
    qjs_op_gosub,
    qjs_op_ret,
    qjs_op_nip_catch,
    qjs_op_to_object,
    qjs_op_to_propkey,
    qjs_op_to_propkey2,
    qjs_op_with_get_var,
    qjs_op_with_put_var,
    qjs_op_with_delete_var,
    qjs_op_with_make_ref,
    qjs_op_with_get_ref,
    qjs_op_with_get_ref_undef,
    qjs_op_make_loc_ref,
    qjs_op_make_arg_ref,
    qjs_op_make_var_ref_ref,
    qjs_op_make_var_ref,
    qjs_op_for_in_start,
    qjs_op_for_of_start,
    qjs_op_for_await_of_start,
    qjs_op_for_in_next,
    qjs_op_for_of_next,
    qjs_op_iterator_check_object,
    qjs_op_iterator_get_value_done,
    qjs_op_iterator_close,
    qjs_op_iterator_next,
    qjs_op_iterator_call,
    qjs_op_initial_yield,
    qjs_op_yield,
    qjs_op_yield_star,
    qjs_op_async_yield_star,
    qjs_op_await,
    qjs_op_neg,
    qjs_op_plus,
    qjs_op_dec,
    qjs_op_inc,
    qjs_op_post_dec,
    qjs_op_post_inc,
    qjs_op_dec_loc,
    qjs_op_inc_loc,
    qjs_op_add_loc,
    qjs_op_not,
    qjs_op_lnot,
    qjs_op_typeof,
    qjs_op_delete,
    qjs_op_delete_var,
    qjs_op_mul,
    qjs_op_div,
    qjs_op_mod,
    qjs_op_add,
    qjs_op_sub,
    qjs_op_pow,
    qjs_op_shl,
    qjs_op_sar,
    qjs_op_shr,
    qjs_op_lt,
    qjs_op_lte,
    qjs_op_gt,
    qjs_op_gte,
    qjs_op_instanceof,
    qjs_op_in,
    qjs_op_eq,
    qjs_op_neq,
    qjs_op_strict_eq,
    qjs_op_strict_neq,
    qjs_op_and,
    qjs_op_xor,
    qjs_op_or,
    qjs_op_is_undefined_or_null,
    qjs_op_private_in,
    qjs_op_mul_pow10,
    qjs_op_math_mod,
    qjs_op_nop,
    /* short opcodes (SHORT_OPCODES) */
    qjs_op_push_minus1,
    qjs_op_push_0,
    qjs_op_push_1,
    qjs_op_push_2,
    qjs_op_push_3,
    qjs_op_push_4,
    qjs_op_push_5,
    qjs_op_push_6,
    qjs_op_push_7,
    qjs_op_push_i8,
    qjs_op_push_i16,
    qjs_op_push_const8,
    qjs_op_fclosure8,
    qjs_op_push_empty_string,
    qjs_op_get_loc8,
    qjs_op_put_loc8,
    qjs_op_set_loc8,
    qjs_op_get_loc0,
    qjs_op_get_loc1,
    qjs_op_get_loc2,
    qjs_op_get_loc3,
    qjs_op_put_loc0,
    qjs_op_put_loc1,
    qjs_op_put_loc2,
    qjs_op_put_loc3,
    qjs_op_set_loc0,
    qjs_op_set_loc1,
    qjs_op_set_loc2,
    qjs_op_set_loc3,
    qjs_op_get_arg0,
    qjs_op_get_arg1,
    qjs_op_get_arg2,
    qjs_op_get_arg3,
    qjs_op_put_arg0,
    qjs_op_put_arg1,
    qjs_op_put_arg2,
    qjs_op_put_arg3,
    qjs_op_set_arg0,
    qjs_op_set_arg1,
    qjs_op_set_arg2,
    qjs_op_set_arg3,
    qjs_op_get_var_ref0,
    qjs_op_get_var_ref1,
    qjs_op_get_var_ref2,
    qjs_op_get_var_ref3,
    qjs_op_put_var_ref0,
    qjs_op_put_var_ref1,
    qjs_op_put_var_ref2,
    qjs_op_put_var_ref3,
    qjs_op_set_var_ref0,
    qjs_op_set_var_ref1,
    qjs_op_set_var_ref2,
    qjs_op_set_var_ref3,
    qjs_op_get_length,
    qjs_op_if_false8,
    qjs_op_if_true8,
    qjs_op_goto8,
    qjs_op_goto16,
    qjs_op_call0,
    qjs_op_call1,
    qjs_op_call2,
    qjs_op_call3,
    qjs_op_is_undefined,
    qjs_op_is_null,
    qjs_op_typeof_is_undefined,
    qjs_op_typeof_is_function,
    qjs_op_count,                /* sentinel = number of valid opcodes */
};

/* =========================================================
 * Static opcode info table
 *
 * NOTE: This must be kept in EXACT sync with the enum above
 * and with quickjs-opcode.h.
 * ========================================================= */
static const qjs_op_info_t qjs_op_info[] = {
    /* 0x00 */ { "invalid",          1,  0,  0, QJS_FMT_none },
    /* 0x01 */ { "push_i32",         5,  0,  1, QJS_FMT_i32 },
    /* 0x02 */ { "push_const",       5,  0,  1, QJS_FMT_const },
    /* 0x03 */ { "fclosure",         5,  0,  1, QJS_FMT_const },
    /* 0x04 */ { "push_atom_value",  5,  0,  1, QJS_FMT_atom },
    /* 0x05 */ { "private_symbol",   5,  0,  1, QJS_FMT_atom },
    /* 0x06 */ { "undefined",        1,  0,  1, QJS_FMT_none },
    /* 0x07 */ { "null",             1,  0,  1, QJS_FMT_none },
    /* 0x08 */ { "push_this",        1,  0,  1, QJS_FMT_none },
    /* 0x09 */ { "push_false",       1,  0,  1, QJS_FMT_none },
    /* 0x0A */ { "push_true",        1,  0,  1, QJS_FMT_none },
    /* 0x0B */ { "object",           1,  0,  1, QJS_FMT_none },
    /* 0x0C */ { "special_object",   2,  0,  1, QJS_FMT_u8 },
    /* 0x0D */ { "rest",             3,  0,  1, QJS_FMT_u16 },
    /* 0x0E */ { "drop",             1,  1,  0, QJS_FMT_none },
    /* 0x0F */ { "nip",              1,  2,  1, QJS_FMT_none },
    /* 0x10 */ { "nip1",             1,  3,  2, QJS_FMT_none },
    /* 0x11 */ { "dup",              1,  1,  2, QJS_FMT_none },
    /* 0x12 */ { "dup1",             1,  2,  3, QJS_FMT_none },
    /* 0x13 */ { "dup2",             1,  2,  4, QJS_FMT_none },
    /* 0x14 */ { "dup3",             1,  3,  6, QJS_FMT_none },
    /* 0x15 */ { "insert2",          1,  2,  3, QJS_FMT_none },
    /* 0x16 */ { "insert3",          1,  3,  4, QJS_FMT_none },
    /* 0x17 */ { "insert4",          1,  4,  5, QJS_FMT_none },
    /* 0x18 */ { "perm3",            1,  3,  3, QJS_FMT_none },
    /* 0x19 */ { "perm4",            1,  4,  4, QJS_FMT_none },
    /* 0x1A */ { "perm5",            1,  5,  5, QJS_FMT_none },
    /* 0x1B */ { "swap",             1,  2,  2, QJS_FMT_none },
    /* 0x1C */ { "swap2",            1,  4,  4, QJS_FMT_none },
    /* 0x1D */ { "rot3l",            1,  3,  3, QJS_FMT_none },
    /* 0x1E */ { "rot3r",            1,  3,  3, QJS_FMT_none },
    /* 0x1F */ { "rot4l",            1,  4,  4, QJS_FMT_none },
    /* 0x20 */ { "rot5l",            1,  5,  5, QJS_FMT_none },
    /* 0x21 */ { "call_constructor", 3,  2,  1, QJS_FMT_npop },
    /* 0x22 */ { "call",             3,  1,  1, QJS_FMT_npop },
    /* 0x23 */ { "tail_call",        3,  1,  0, QJS_FMT_npop },
    /* 0x24 */ { "call_method",      3,  2,  1, QJS_FMT_npop },
    /* 0x25 */ { "tail_call_method", 3,  2,  0, QJS_FMT_npop },
    /* 0x26 */ { "array_from",       3,  0,  1, QJS_FMT_npop },
    /* 0x27 */ { "apply",            3,  3,  1, QJS_FMT_u16 },
    /* 0x28 */ { "return",           1,  1,  0, QJS_FMT_none },
    /* 0x29 */ { "return_undef",     1,  0,  0, QJS_FMT_none },
    /* 0x2A */ { "check_ctor_return",1,  1,  2, QJS_FMT_none },
    /* 0x2B */ { "check_ctor",       1,  0,  0, QJS_FMT_none },
    /* 0x2C */ { "check_brand",      1,  2,  2, QJS_FMT_none },
    /* 0x2D */ { "add_brand",        1,  2,  0, QJS_FMT_none },
    /* 0x2E */ { "return_async",     1,  1,  0, QJS_FMT_none },
    /* 0x2F */ { "throw",            1,  1,  0, QJS_FMT_none },
    /* 0x30 */ { "throw_error",      6,  0,  0, QJS_FMT_atom_u8 },
    /* 0x31 */ { "eval",             5,  1,  1, QJS_FMT_npop_u16 },
    /* 0x32 */ { "apply_eval",       3,  2,  1, QJS_FMT_u16 },
    /* 0x33 */ { "regexp",           1,  2,  1, QJS_FMT_none },
    /* 0x34 */ { "get_super",        1,  1,  1, QJS_FMT_none },
    /* 0x35 */ { "import",           1,  1,  1, QJS_FMT_none },
    /* 0x36 */ { "check_var",        5,  0,  1, QJS_FMT_atom },
    /* 0x37 */ { "get_var_undef",    5,  0,  1, QJS_FMT_atom },
    /* 0x38 */ { "get_var",          5,  0,  1, QJS_FMT_atom },
    /* 0x39 */ { "put_var",          5,  1,  0, QJS_FMT_atom },
    /* 0x3A */ { "put_var_init",     5,  1,  0, QJS_FMT_atom },
    /* 0x3B */ { "put_var_strict",   5,  2,  0, QJS_FMT_atom },
    /* 0x3C */ { "get_ref_value",    1,  2,  3, QJS_FMT_none },
    /* 0x3D */ { "put_ref_value",    1,  3,  0, QJS_FMT_none },
    /* 0x3E */ { "define_var",       6,  0,  0, QJS_FMT_atom_u8 },
    /* 0x3F */ { "check_define_var", 6,  0,  0, QJS_FMT_atom_u8 },
    /* 0x40 */ { "define_func",      6,  1,  0, QJS_FMT_atom_u8 },
    /* 0x41 */ { "get_field",        5,  1,  1, QJS_FMT_atom },
    /* 0x42 */ { "get_field2",       5,  1,  2, QJS_FMT_atom },
    /* 0x43 */ { "put_field",        5,  2,  0, QJS_FMT_atom },
    /* 0x44 */ { "get_private_field",1,  2,  1, QJS_FMT_none },
    /* 0x45 */ { "put_private_field",1,  3,  0, QJS_FMT_none },
    /* 0x46 */ { "define_private_field",1, 3, 1, QJS_FMT_none },
    /* 0x47 */ { "get_array_el",     1,  2,  1, QJS_FMT_none },
    /* 0x48 */ { "get_array_el2",    1,  2,  2, QJS_FMT_none },
    /* 0x49 */ { "put_array_el",     1,  3,  0, QJS_FMT_none },
    /* 0x4A */ { "get_super_value",  1,  3,  1, QJS_FMT_none },
    /* 0x4B */ { "put_super_value",  1,  4,  0, QJS_FMT_none },
    /* 0x4C */ { "define_field",     5,  2,  1, QJS_FMT_atom },
    /* 0x4D */ { "set_name",         5,  1,  1, QJS_FMT_atom },
    /* 0x4E */ { "set_name_computed",1,  2,  2, QJS_FMT_none },
    /* 0x4F */ { "set_proto",        1,  2,  1, QJS_FMT_none },
    /* 0x50 */ { "set_home_object",  1,  2,  2, QJS_FMT_none },
    /* 0x51 */ { "define_array_el",  1,  3,  2, QJS_FMT_none },
    /* 0x52 */ { "append",           1,  3,  2, QJS_FMT_none },
    /* 0x53 */ { "copy_data_properties", 2, 3, 3, QJS_FMT_u8 },
    /* 0x54 */ { "define_method",    6,  2,  1, QJS_FMT_atom_u8 },
    /* 0x55 */ { "define_method_computed", 2, 3, 1, QJS_FMT_u8 },
    /* 0x56 */ { "define_class",     6,  2,  2, QJS_FMT_atom_u8 },
    /* 0x57 */ { "define_class_computed", 6, 3, 3, QJS_FMT_atom_u8 },
    /* 0x58 */ { "get_loc",          3,  0,  1, QJS_FMT_loc },
    /* 0x59 */ { "put_loc",          3,  1,  0, QJS_FMT_loc },
    /* 0x5A */ { "set_loc",          3,  1,  1, QJS_FMT_loc },
    /* 0x5B */ { "get_arg",          3,  0,  1, QJS_FMT_arg },
    /* 0x5C */ { "put_arg",          3,  1,  0, QJS_FMT_arg },
    /* 0x5D */ { "set_arg",          3,  1,  1, QJS_FMT_arg },
    /* 0x5E */ { "get_var_ref",      3,  0,  1, QJS_FMT_var_ref },
    /* 0x5F */ { "put_var_ref",      3,  1,  0, QJS_FMT_var_ref },
    /* 0x60 */ { "set_var_ref",      3,  1,  1, QJS_FMT_var_ref },
    /* 0x61 */ { "set_loc_uninitialized", 3, 0, 0, QJS_FMT_loc },
    /* 0x62 */ { "get_loc_check",    3,  0,  1, QJS_FMT_loc },
    /* 0x63 */ { "put_loc_check",    3,  1,  0, QJS_FMT_loc },
    /* 0x64 */ { "put_loc_check_init", 3, 1, 0, QJS_FMT_loc },
    /* 0x65 */ { "get_loc_checkthis", 3, 0, 1, QJS_FMT_loc },
    /* 0x66 */ { "get_var_ref_check", 3, 0, 1, QJS_FMT_var_ref },
    /* 0x67 */ { "put_var_ref_check", 3, 1, 0, QJS_FMT_var_ref },
    /* 0x68 */ { "put_var_ref_check_init", 3, 1, 0, QJS_FMT_var_ref },
    /* 0x69 */ { "close_loc",        3,  0,  0, QJS_FMT_loc },
    /* 0x6A */ { "if_false",         5,  1,  0, QJS_FMT_label },
    /* 0x6B */ { "if_true",          5,  1,  0, QJS_FMT_label },
    /* 0x6C */ { "goto",             5,  0,  0, QJS_FMT_label },
    /* 0x6D */ { "catch",            5,  0,  1, QJS_FMT_label },
    /* 0x6E */ { "gosub",            5,  0,  0, QJS_FMT_label },
    /* 0x6F */ { "ret",              1,  1,  0, QJS_FMT_none },
    /* 0x70 */ { "nip_catch",        1,  2,  1, QJS_FMT_none },
    /* 0x71 */ { "to_object",        1,  1,  1, QJS_FMT_none },
    /* 0x72 */ { "to_propkey",       1,  1,  1, QJS_FMT_none },
    /* 0x73 */ { "to_propkey2",      1,  2,  2, QJS_FMT_none },
    /* 0x74 */ { "with_get_var",     10, 1,  0, QJS_FMT_atom_label_u8 },
    /* 0x75 */ { "with_put_var",     10, 2,  1, QJS_FMT_atom_label_u8 },
    /* 0x76 */ { "with_delete_var",  10, 1,  0, QJS_FMT_atom_label_u8 },
    /* 0x77 */ { "with_make_ref",    10, 1,  0, QJS_FMT_atom_label_u8 },
    /* 0x78 */ { "with_get_ref",     10, 1,  0, QJS_FMT_atom_label_u8 },
    /* 0x79 */ { "with_get_ref_undef", 10, 1, 0, QJS_FMT_atom_label_u8 },
    /* 0x7A */ { "make_loc_ref",     7,  0,  2, QJS_FMT_atom_u16 },
    /* 0x7B */ { "make_arg_ref",     7,  0,  2, QJS_FMT_atom_u16 },
    /* 0x7C */ { "make_var_ref_ref", 7,  0,  2, QJS_FMT_atom_u16 },
    /* 0x7D */ { "make_var_ref",     5,  0,  2, QJS_FMT_atom },
    /* 0x7E */ { "for_in_start",     1,  1,  1, QJS_FMT_none },
    /* 0x7F */ { "for_of_start",     1,  1,  3, QJS_FMT_none },
    /* 0x80 */ { "for_await_of_start", 1, 1, 3, QJS_FMT_none },
    /* 0x81 */ { "for_in_next",      1,  1,  3, QJS_FMT_none },
    /* 0x82 */ { "for_of_next",      2,  3,  5, QJS_FMT_u8 },
    /* 0x83 */ { "iterator_check_object", 1, 1, 1, QJS_FMT_none },
    /* 0x84 */ { "iterator_get_value_done", 1, 1, 2, QJS_FMT_none },
    /* 0x85 */ { "iterator_close",   1,  3,  0, QJS_FMT_none },
    /* 0x86 */ { "iterator_next",    1,  4,  4, QJS_FMT_none },
    /* 0x87 */ { "iterator_call",    2,  4,  5, QJS_FMT_u8 },
    /* 0x88 */ { "initial_yield",    1,  0,  0, QJS_FMT_none },
    /* 0x89 */ { "yield",            1,  1,  2, QJS_FMT_none },
    /* 0x8A */ { "yield_star",       1,  1,  2, QJS_FMT_none },
    /* 0x8B */ { "async_yield_star", 1,  1,  2, QJS_FMT_none },
    /* 0x8C */ { "await",            1,  1,  1, QJS_FMT_none },
    /* 0x8D */ { "neg",              1,  1,  1, QJS_FMT_none },
    /* 0x8E */ { "plus",             1,  1,  1, QJS_FMT_none },
    /* 0x8F */ { "dec",              1,  1,  1, QJS_FMT_none },
    /* 0x90 */ { "inc",              1,  1,  1, QJS_FMT_none },
    /* 0x91 */ { "post_dec",         1,  1,  2, QJS_FMT_none },
    /* 0x92 */ { "post_inc",         1,  1,  2, QJS_FMT_none },
    /* 0x93 */ { "dec_loc",          2,  0,  0, QJS_FMT_loc8 },
    /* 0x94 */ { "inc_loc",          2,  0,  0, QJS_FMT_loc8 },
    /* 0x95 */ { "add_loc",          2,  1,  0, QJS_FMT_loc8 },
    /* 0x96 */ { "not",              1,  1,  1, QJS_FMT_none },
    /* 0x97 */ { "lnot",             1,  1,  1, QJS_FMT_none },
    /* 0x98 */ { "typeof",           1,  1,  1, QJS_FMT_none },
    /* 0x99 */ { "delete",           1,  2,  1, QJS_FMT_none },
    /* 0x9A */ { "delete_var",       5,  0,  1, QJS_FMT_atom },
    /* 0x9B */ { "mul",              1,  2,  1, QJS_FMT_none },
    /* 0x9C */ { "div",              1,  2,  1, QJS_FMT_none },
    /* 0x9D */ { "mod",              1,  2,  1, QJS_FMT_none },
    /* 0x9E */ { "add",              1,  2,  1, QJS_FMT_none },
    /* 0x9F */ { "sub",              1,  2,  1, QJS_FMT_none },
    /* 0xA0 */ { "pow",              1,  2,  1, QJS_FMT_none },
    /* 0xA1 */ { "shl",              1,  2,  1, QJS_FMT_none },
    /* 0xA2 */ { "sar",              1,  2,  1, QJS_FMT_none },
    /* 0xA3 */ { "shr",              1,  2,  1, QJS_FMT_none },
    /* 0xA4 */ { "lt",               1,  2,  1, QJS_FMT_none },
    /* 0xA5 */ { "lte",              1,  2,  1, QJS_FMT_none },
    /* 0xA6 */ { "gt",               1,  2,  1, QJS_FMT_none },
    /* 0xA7 */ { "gte",              1,  2,  1, QJS_FMT_none },
    /* 0xA8 */ { "instanceof",       1,  2,  1, QJS_FMT_none },
    /* 0xA9 */ { "in",               1,  2,  1, QJS_FMT_none },
    /* 0xAA */ { "eq",               1,  2,  1, QJS_FMT_none },
    /* 0xAB */ { "neq",              1,  2,  1, QJS_FMT_none },
    /* 0xAC */ { "strict_eq",        1,  2,  1, QJS_FMT_none },
    /* 0xAD */ { "strict_neq",       1,  2,  1, QJS_FMT_none },
    /* 0xAE */ { "and",              1,  2,  1, QJS_FMT_none },
    /* 0xAF */ { "xor",              1,  2,  1, QJS_FMT_none },
    /* 0xB0 */ { "or",               1,  2,  1, QJS_FMT_none },
    /* 0xB1 */ { "is_undefined_or_null", 1, 1, 1, QJS_FMT_none },
    /* 0xB2 */ { "private_in",       1,  2,  1, QJS_FMT_none },
    /* 0xB3 */ { "mul_pow10",        1,  2,  1, QJS_FMT_none },
    /* 0xB4 */ { "math_mod",         1,  2,  1, QJS_FMT_none },
    /* 0xB5 */ { "nop",              1,  0,  0, QJS_FMT_none },
    /* 0xB6 */ { "push_minus1",      1,  0,  1, QJS_FMT_none_int },
    /* 0xB7 */ { "push_0",           1,  0,  1, QJS_FMT_none_int },
    /* 0xB8 */ { "push_1",           1,  0,  1, QJS_FMT_none_int },
    /* 0xB9 */ { "push_2",           1,  0,  1, QJS_FMT_none_int },
    /* 0xBA */ { "push_3",           1,  0,  1, QJS_FMT_none_int },
    /* 0xBB */ { "push_4",           1,  0,  1, QJS_FMT_none_int },
    /* 0xBC */ { "push_5",           1,  0,  1, QJS_FMT_none_int },
    /* 0xBD */ { "push_6",           1,  0,  1, QJS_FMT_none_int },
    /* 0xBE */ { "push_7",           1,  0,  1, QJS_FMT_none_int },
    /* 0xBF */ { "push_i8",          2,  0,  1, QJS_FMT_i8 },
    /* 0xC0 */ { "push_i16",         3,  0,  1, QJS_FMT_i16 },
    /* 0xC1 */ { "push_const8",      2,  0,  1, QJS_FMT_const8 },
    /* 0xC2 */ { "fclosure8",        2,  0,  1, QJS_FMT_const8 },
    /* 0xC3 */ { "push_empty_string",1,  0,  1, QJS_FMT_none },
    /* 0xC4 */ { "get_loc8",         2,  0,  1, QJS_FMT_loc8 },
    /* 0xC5 */ { "put_loc8",         2,  1,  0, QJS_FMT_loc8 },
    /* 0xC6 */ { "set_loc8",         2,  1,  1, QJS_FMT_loc8 },
    /* 0xC7 */ { "get_loc0",         1,  0,  1, QJS_FMT_none_loc },
    /* 0xC8 */ { "get_loc1",         1,  0,  1, QJS_FMT_none_loc },
    /* 0xC9 */ { "get_loc2",         1,  0,  1, QJS_FMT_none_loc },
    /* 0xCA */ { "get_loc3",         1,  0,  1, QJS_FMT_none_loc },
    /* 0xCB */ { "put_loc0",         1,  1,  0, QJS_FMT_none_loc },
    /* 0xCC */ { "put_loc1",         1,  1,  0, QJS_FMT_none_loc },
    /* 0xCD */ { "put_loc2",         1,  1,  0, QJS_FMT_none_loc },
    /* 0xCE */ { "put_loc3",         1,  1,  0, QJS_FMT_none_loc },
    /* 0xCF */ { "set_loc0",         1,  1,  1, QJS_FMT_none_loc },
    /* 0xD0 */ { "set_loc1",         1,  1,  1, QJS_FMT_none_loc },
    /* 0xD1 */ { "set_loc2",         1,  1,  1, QJS_FMT_none_loc },
    /* 0xD2 */ { "set_loc3",         1,  1,  1, QJS_FMT_none_loc },
    /* 0xD3 */ { "get_arg0",         1,  0,  1, QJS_FMT_none_arg },
    /* 0xD4 */ { "get_arg1",         1,  0,  1, QJS_FMT_none_arg },
    /* 0xD5 */ { "get_arg2",         1,  0,  1, QJS_FMT_none_arg },
    /* 0xD6 */ { "get_arg3",         1,  0,  1, QJS_FMT_none_arg },
    /* 0xD7 */ { "put_arg0",         1,  1,  0, QJS_FMT_none_arg },
    /* 0xD8 */ { "put_arg1",         1,  1,  0, QJS_FMT_none_arg },
    /* 0xD9 */ { "put_arg2",         1,  1,  0, QJS_FMT_none_arg },
    /* 0xDA */ { "put_arg3",         1,  1,  0, QJS_FMT_none_arg },
    /* 0xDB */ { "set_arg0",         1,  1,  1, QJS_FMT_none_arg },
    /* 0xDC */ { "set_arg1",         1,  1,  1, QJS_FMT_none_arg },
    /* 0xDD */ { "set_arg2",         1,  1,  1, QJS_FMT_none_arg },
    /* 0xDE */ { "set_arg3",         1,  1,  1, QJS_FMT_none_arg },
    /* 0xDF */ { "get_var_ref0",     1,  0,  1, QJS_FMT_none_var_ref },
    /* 0xE0 */ { "get_var_ref1",     1,  0,  1, QJS_FMT_none_var_ref },
    /* 0xE1 */ { "get_var_ref2",     1,  0,  1, QJS_FMT_none_var_ref },
    /* 0xE2 */ { "get_var_ref3",     1,  0,  1, QJS_FMT_none_var_ref },
    /* 0xE3 */ { "put_var_ref0",     1,  1,  0, QJS_FMT_none_var_ref },
    /* 0xE4 */ { "put_var_ref1",     1,  1,  0, QJS_FMT_none_var_ref },
    /* 0xE5 */ { "put_var_ref2",     1,  1,  0, QJS_FMT_none_var_ref },
    /* 0xE6 */ { "put_var_ref3",     1,  1,  0, QJS_FMT_none_var_ref },
    /* 0xE7 */ { "set_var_ref0",     1,  1,  1, QJS_FMT_none_var_ref },
    /* 0xE8 */ { "set_var_ref1",     1,  1,  1, QJS_FMT_none_var_ref },
    /* 0xE9 */ { "set_var_ref2",     1,  1,  1, QJS_FMT_none_var_ref },
    /* 0xEA */ { "set_var_ref3",     1,  1,  1, QJS_FMT_none_var_ref },
    /* 0xEB */ { "get_length",       1,  1,  1, QJS_FMT_none },
    /* 0xEC */ { "if_false8",        2,  1,  0, QJS_FMT_label8 },
    /* 0xED */ { "if_true8",         2,  1,  0, QJS_FMT_label8 },
    /* 0xEE */ { "goto8",            2,  0,  0, QJS_FMT_label8 },
    /* 0xEF */ { "goto16",           3,  0,  0, QJS_FMT_label16 },
    /* 0xF0 */ { "call0",            1,  1,  1, QJS_FMT_npopx },
    /* 0xF1 */ { "call1",            1,  1,  1, QJS_FMT_npopx },
    /* 0xF2 */ { "call2",            1,  1,  1, QJS_FMT_npopx },
    /* 0xF3 */ { "call3",            1,  1,  1, QJS_FMT_npopx },
    /* 0xF4 */ { "is_undefined",     1,  1,  1, QJS_FMT_none },
    /* 0xF5 */ { "is_null",          1,  1,  1, QJS_FMT_none },
    /* 0xF6 */ { "typeof_is_undefined", 1, 1, 1, QJS_FMT_none },
    /* 0xF7 */ { "typeof_is_function", 1, 1, 1, QJS_FMT_none },
};

/* Compile-time assertion: table size matches enum count */
#define QJS_OP_INFO_COUNT ((int)(sizeof(qjs_op_info) / sizeof(qjs_op_info[0])))

#endif /* QJS_OPCODES_H */
